name: Ci/CD pipeline
on:
  push:
   branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
      - name: build,push, iamge
        env:
          docker_username: ${{ secrets.username }}
          image: my-image
        run: |
          docker build -t $docker_username/$image .
          docker push $docker_username/$image:latest

          
